version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    links: 
      - mongodb
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
volumes:
  mongodata: